version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    expose:
      [6379]
    volumes: 
      - cache:/data
  mongo:
      image: mongo:latest
      container_name: 'mongo-bike-api'
      restart: always
      environment:
          MONGO_INITDB_DATABASE: bike-api
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: xxmaster
      volumes:
          - bike_vol:/data/db
      networks:
          default:
      ports:
          - '27017-27019:27017-27019'  
  nodejs:
        build:
            context: ./Server
        depends_on: 
            - mongo
        restart: always
        networks:
            default:
        ports:
            - "9000:9000"
        container_name: bike_server
volumes:
  bike_vol:
  cache:
    driver: local

networks:
    default:
        driver: bridge